package arreglos;

public enum Lista_Materias {MICROECONOMIA1,MICROECONOMIA2,MICROECONOMIA3,MACROECONOMIA1,MACROECONOMIA2,MACROECONOMIA3,
	LOGICA,CALCULO1,CALCULO2,ECONOMETRIA_BASICA,ECONOMETRIA_INTERMEDIA,PROBABILIDAD,ESTADISTICA,HISTORIA_GENERAL,
	HISTORIA_COLOMBIANA,DOCTRINAS,INTRODUCCION,ECONOMIA_MATEMATICA,ALGEBRA

}
